<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" name="L5_CreateClient(failed)" tests="3" failures="1" timestamp="6 May 2014 11:13:17 GMT" time="24.494" errors="0">
  <testcase name="L5_Create_client_Validations" time="7.575" classname="scenarios.L5_CreateClient"/>
  <testcase name="L5_Create_client" time="16.762" classname="scenarios.L5_CreateClient">
    <failure type="java.lang.AssertionError" message="Validate that success message is displayed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validate that success message is displayed. expected [true] but found [false]
	at framework.GeneralMethods.Textvalidation(GeneralMethods.java:287)
	at framework.GeneralMethods.action(GeneralMethods.java:63)
	at framework.Standard.StandardM1(Standard.java:21)
	at scenarios.L5_CreateClient.L5_Create_client(L5_CreateClient.java:55)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- L5_Create_client -->
  <testcase name="L5_ResetPassword" time="0.0" classname="scenarios.L5_CreateClient">
    <skipped/>
  </testcase> <!-- L5_ResetPassword -->
</testsuite> <!-- L5_CreateClient(failed) -->
